### ISSUE TITLE
Reference?

### ISSUE THREAD

**Issue by augustfly** [fedriani/sedcreator#2]
Hi, 

I am a data editor with the AAS Journals. We have authors using your software in their research, but when they go to cite it, your recommendation:

> This research made use of sedcreator (Fedriani et al. 2022).

Is incomplete because there are no details about the "Fedriani et al. 2022" reference. Can you provide these details in your ReadMe file? Do you mean for your users to cite the GitHub repository directly? Or will you initiate a release and deposit a version to Zenodo? In either case I might suggest including sample BibTeX for the recommended citation. If that citation is for GitHub then I would add this bibtex to your ReadMe file:

```
@software(sedcreator,
author={Ruben Fedriani},
title={fedriani/sedcreator},
version={Commit: 165c191},
publisher={GitHub},
url={https://github.com/fedriani/sedcreator/},
year={2022}
}

```

**Comment by fedriani** [comment]
Hello August,


Thanks - I am very glad people are using the package.


The current situation of the package is that is attached to the scientific publication 'The SOFIA Massive (SOMA) Star Formation Survey. IV. Isolated Protostars', which I submitted last week to ApJ. I also submitted the paper to the arxiv and it appears now in ADS (see link below):


https://ui.adsabs.harvard.edu/abs/2022arXiv220511422F/abstract



While the current version of sedcreator is usable and stable, I was waiting to formal acceptance from AAS to release version 1.0.0 and tell the user the reference the ApJ paper.


I suggest that the early users cite the arxiv paper and hopefully before their papers get accepted they can update to the final ApJ publication citation.


How does this sound? I will be happy to provide any further information.


All the best,

Rubén


PS: In fact, while refereeing of my paper, I will be including updates to the code and documentation.


***************************************************************
Dr. Rubén Fedriani
Marie Sklodowska Curie Postdoctoral Fellow
Chalmers University of Technology
Department of Space, Earth, and Environment
EDIT Johanneberg, Hörsalsvägen 11
SE-412 96, Gothenburg (Sweden)
www.chalmers.se<http://www.chalmers.se/>
***************************************************************

________________________________
From: August Muench ***@***.***>
Sent: 23 May 2022 14:33:38
To: fedriani/sedcreator
Cc: Subscribed
Subject: [fedriani/sedcreator] Reference? (Issue #2)


Hi,

I am a data editor with the AAS Journals. We have authors using your software in their research, but when they go to cite it, your recommendation:

This research made use of sedcreator (Fedriani et al. 2022).

Is incomplete because there are no details about the "Fedriani et al. 2022" reference. Can you provide these details in your ReadMe file? Do you mean for your users to cite the GitHub repository directly? Or will you initiate a release and deposit a version to Zenodo? In either case I might suggest including sample BibTeX for the recommended citation. If that citation is for GitHub then I would add this bibtex to your ReadMe file:

@software(sedcreator,
author={Ruben Fedriani},
title={fedriani/sedcreator},
version={Commit: 165c191},
publisher={GitHub},
url={https://github.com/fedriani/sedcreator/},
year={2022}
}

**Comment by augustfly** [comment]
That all makes sense. Thanks for your reply!
